version: "3.9"

services:
  backend:
    build: ./backend
    container_name: media_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - /media/ubuntu/ExternalDrive/media-gallery/uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: media_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      
  mysql:
    image: mysql:8.4
    container_name: media_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: media_gallery
      MYSQL_USER: mediauser
      MYSQL_PASSWORD: mediapassword
    volumes:
      - /media/ubuntu/ExternalDrive/media-gallery/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: media_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CF_TUNNEL_TOKEN}
    depends_on:
      - backend